travis:
  secure:
    BINSTAR_TOKEN: E9+aN+kBE6N0zxMwz45BGsy4LYbI1VSo74uVkVGUVxQzlYnSNmuRaBcAbu/IAhGy45wt5FQtuccUbUzUWakWzUqa39Vn25nzlKCIksZHIRxX+v/9LBxRdMoZY1PNmnGwa6KgWlxCtgH8vGRiegZYquS+oyREM/O2qGh1jR/ufrRxIl7ZSK77DAONm4i3jKiBcHFBjOvpgroKe4gP8V7hTRKK8z9jPMeSo06c6q79UoLk/QP2gz8dI9sdKTzQRlVB45/GoYeBZU8jg8iWtee2wHo7DBWJypTwkJT78v5zJc055d/swH1VqIjLDpH2AS4bBG25/Z7wdKNYFN5tR1GrFUU7Jia9WRkItwfP1qwOqXgJUeSpDdh6XteCKuJUxc445kGejcPHwJZwRT9Kv3elWbjwtlYTZE3oPqP7g5DKaME1EFYW99ZDN1ArsGa5A2aiu5h4xpZdKEXug67u0PtxwZSZZC2ABo9eEkslav0SOMMOvXUPbApyEoHyTtWvdRxqsfxnnFbiZMyr4kEETsqz99+FPlrVDL2fT/MmlyoQ0X8oWx8YYCr9vhAqeYep5lJqX76MRVjqnDCx5I1yq7hx0VlFYv6EOpb3IiT2VEftmyGruDmd34xWlxSQ6C5LiZ7F8qF3/Sadt2uKnMhqQVEoOJ5UiOGeBNF9xDVal8C+6nM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
